# Generated by Django 4.2.4 on 2023-08-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msg_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="birth_day",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
