# Generated by Django 4.2.4 on 2023-08-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msg_app", "0002_alter_usermodel_birth_day"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="user",
            new_name="users",
        ),
    ]
