# Generated by Django 4.2.4 on 2023-08-22 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("msg_app", "0003_rename_user_message_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="users",
        ),
        migrations.AddField(
            model_name="message",
            name="users",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
