# Generated by Django 4.2.4 on 2023-08-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msg_app", "0004_remove_message_users_message_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="users",
            new_name="user",
        ),
    ]
