# Generated by Django 4.2.4 on 2023-08-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msg_app", "0005_rename_users_message_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="telegram_id",
            field=models.CharField(
                max_length=60, unique=True, verbose_name="User's telegram Id"
            ),
        ),
    ]
